### ISSUE TITLE
Review: txpActiveUsers.sql

### ISSUE THREAD

**Issue by rayborn** [mozilla/testpilot_metrics#7]
@emtwo: Please take a look at: [txpActiveUsers.sql](https://github.com/mozilla/testpilot_metrics/blob/master/testpilot_all_metrics/txpActiveUsers.sql)

If we're doing SQL reviews, that's a good place to start.

**Comment by rayborn** [comment]
Per our conversation Wednesday, everything should be resolved now.  Feel free to take a look.

**Comment by emtwo** [comment]
I've taken a look at this query and it looks good to me! I just have a couple of comments:

1. The data seems to end of Aug 4th. Is that just because Presto doesn't have the latest data or is something else going on?

2. From this query I can't see how mau/dau are actually calculated but it would be nice to validate this at well... I understand this is probably done in a notebook somewhere? Also, I looked at the Activity Stream daily active users and the numbers look fairly close. I may try another query on AS for a better comparison.

**Comment by rayborn** [comment]
1. Yep, that's an issue that we're tracking in [Trello here](https://trello.com/c/cA4JLNpY/7-relaunch-mau-dau-pipeline-s-e-g-why-does-our-data-just-stop)
2. It comes from MReid's function [here](https://github.com/mozilla/python_moztelemetry/blob/master/moztelemetry/standards.py), but @ilanasegall could get you the implementation notebook.  However, I feel that the scope of this review is the use of the Presto data not the pipeline prior to it, and that should be a separate review.

Thanks

**Comment by emtwo** [comment]
Cool thanks for the links @rayborn! Agreed that that's out of the scope of this review I was just curious :)

I'd say r+ and we can call this one reviewed!

**Comment by ghost** [comment]
Closed out :smile:
